### ISSUE TITLE
Ordering in the django admin panel.

### ISSUE THREAD

**Issue by RajatShenoi** [RajatShenoi/SocialNetwork#3]
While creating a new user via the admin interface, the ordering of the fields are not ideal. Rearrange them to form a meaningful order.

**Comment by RajatShenoi** [comment]
You will need to branch out from the "implement accounts app" branch to fix this issue since these changes haven't been merged to "main" yet.

**Comment by RajatShenoi** [comment]
> hello @RajatShenoi  i want to work on this issue could u please assign this to me

Thanks for working on this, I've assigned you.

**Comment by seabeePraveen** [comment]
@RajatShenoi i have cloned the repo and i didn't found any apps in the main branch so i have pulled the other branch 1-implement-accounts branch and this is what i found tell me what i have to make changes to make the order like i dont have any data 
so please share a screenshot if possible so i could understand way better
![image](https://github.com/RajatShenoi/SocialNetwork/assets/88821454/38e20aa8-669e-47af-b6ce-eb13148ba39e)

**Comment by RajatShenoi** [comment]
@seabeePraveen. First of all, yes, as mentioned before, you have to **branch out** from the **1-implement-accounts-app** branch and then implement the edits and then raise a PR for merging. The complete steps to contribute are in [CONTRIBUTING.md](https://github.com/RajatShenoi/SocialNetwork/blob/main/CONTRIBUTING.md)

The problem we aim to fix here is just the design, as you can see the screenshots below, (while creating a new user via the admin panel), this is the order in which the fields are shown. The order given below somehow doesn't make sense to me.

<img width="1280" alt="Screenshot 2023-10-11 at 1 55 28 PM" src="https://github.com/RajatShenoi/SocialNetwork/assets/48760956/7efcc390-ad63-4977-9223-f4b265d7ce8c">
<img width="1280" alt="Screenshot 2023-10-11 at 1 55 41 PM" src="https://github.com/RajatShenoi/SocialNetwork/assets/48760956/750b255a-1e2a-43ab-8bad-c910801b2333">

What you need to do is rearrange them to a meaningful (or a more obvious) order. For example: 

1. First Name
2. Last Name
3. Username
4. Email
5. Password
6. Bio
7. Avatar
8. Groups
9. User Permissions
10. Active
11. Staff Status
12. Superuser Status
13. Last Login
14. Date Joined

**Comment by seabeePraveen** [comment]
okay so u just want me to take the re-arrange the order of the input fields in the admin panel that's it right?

**Comment by RajatShenoi** [comment]
Yes, that's right. Just rearrangin. Also, **"optionally"**, make the password field in the admin panel "read-only" (don't hide it). Currently, it shows the hash of the user and it can be edited, make it such that it can't be edited, but the hash can be seen.

**Comment by seabeePraveen** [comment]
hello @RajatShenoi i have made the changes that u have asked and made the pull request once check the screenshots
here u can just see the hashed password but u cannot change it and let me know if u need any more changes and merge the Pull Request
![image](https://github.com/RajatShenoi/SocialNetwork/assets/88821454/67746ea9-f340-4a02-9184-021fa7160b12)

**Comment by RajatShenoi** [comment]
Hello @seabeePraveen, thanks a lot for your contribution. It works really nice, you've also added different sections which make it more easier to use. We'll also be including a contributors section in the README and the website soon and will make sure to add your name in it :)

**Comment by seabeePraveen** [comment]
ohh Thank you so much :) and im open to contribute more please mention me if there is any other issue

**Comment by RajatShenoi** [comment]
Sure
